version: '3.1'

services:
  slides:
    image: haydenbr/docker-for-javascript-developers:delhi
    ports:
      - 3000:3000
    volumes:
      - ./dist:/app/dist
      - ./jsconfig.json:/app/jsconfig.json
      - ./package.json:/app/package.json
      - ./postcss.config.js:/app/postcss.config.js
      - ./src:/app/src
      - ./webpack:/app/webpack
